#!/bin/bash

set -eu

PKG_NAME="nas-diff"
PROJECT_ROOT="$(pwd)"
INST_DIR="/tmp/_${PKG_NAME}"
PKG_DIR="/tmp/_${PKG_NAME}_pkg"
PKG_DEST="/image/packages"

. /pkgscripts-ng/include/pkg_util.sh

prepare_dirs() {
    rm -rf "${INST_DIR}" "${PKG_DIR}"
    mkdir -p "${INST_DIR}" "${PKG_DIR}" "${PKG_DEST}" "${PKG_DIR}/scripts"
}

install_payload() {
    cp -a "${PROJECT_ROOT}/payload/." "${INST_DIR}/"
}

install_package_files() {
    cp -a "${PROJECT_ROOT}/conf" "${PKG_DIR}"
    cp -a "${PROJECT_ROOT}/scripts/." "${PKG_DIR}/scripts/"
    chmod 755 "${PKG_DIR}/scripts/"*
    cp -a "${PROJECT_ROOT}/PACKAGE_ICON.PNG" "${PKG_DIR}/PACKAGE_ICON.PNG"
    cp -a "${PROJECT_ROOT}/PACKAGE_ICON_256.PNG" "${PKG_DIR}/PACKAGE_ICON_256.PNG"
    "${PROJECT_ROOT}/INFO.sh" > "${PKG_DIR}/INFO"
}

make_package() {
    pkg_make_package "${INST_DIR}" "${PKG_DIR}"
    pkg_make_spk "${PKG_DIR}" "${PKG_DEST}"
}

prepare_dirs
install_payload
install_package_files
make_package
